apiVersion: v1
kind: ConfigMap
metadata:
  name: pks
  namespace: kube-system
data:
  apl-api: https://api.applariat.io/v1
  apl-api-key:
  apl-cluster-mgr-tag: develop
  conf.json: |
    {
       "api-url": "https://api.applariat.io/v1",
       "propeller-ignore-ssl": "false"
    }
  silent.json: |
    {
    	"questions": [{
    		"section": "general",
    		"title": "action",
    		"text": "Action",
    		"accepted": ["create", "import", "delete"],
    		"answer": "import"
    	}, {
    		"actions": ["create", "import"],
    		"section": "general",
    		"title": "loc_deploy_name",
    		"text": "Cluster name",
    		"answer": "vke1"
    	}, {
    		"actions": ["create", "import"],
    		"section": "general",
    		"title": "provider",
    		"text": "Cloud provider",
    		"accepted": ["aws", "azure", "gke", "metal", "vke", "vsphere"],
    		"answer": "vsphere."
    	}, {
            "section": "general",
            "actions": ["create", "import"],
            "title": "registry_url",
            "text" : "Enter registry url",
            "answer": "harbor.mylab.com/"
        }, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_fqdn",
    		"text": "Enter fqdn or ip for your kubernetes cluster",
    		"answer": "xx.xx.xx.xx"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_port",
    		"text": "Enter port for your kubernetes cluster",
    		"answer": "443"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "auth_type",
    		"text": "What type of authentication ",
    		"accepted": ["basic", "certs"],
    		"answer": "basic"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "user",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user name: ",
    		"answer": "pks1.k8"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "password",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user password: ",
    		"answer": "admin"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "datastore",
    		"text": "Enter datastore name",
    		"answer": "datastore1"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "diskformat",
    		"text": "Enter disk format",
    		"accepted": ["thin", "thick"],
    		"answer": "thin"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_fqdn",
    		"text": "Enter fqdn or ip for your kubernetes cluster",
    		"answer": "xx.xx.xx.xx"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_port",
    		"text": "Enter port for your kubernetes cluster",
    		"answer": "443"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "auth_type",
    		"text": "What type of authentication ",
    		"accepted": ["basic", "certs"],
    		"answer": "basic"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "user",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user name: ",
    		"answer": "pks1.k8"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "password",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user password: ",
    		"answer": "admin"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "datastore",
    		"text": "Enter datastore name",
    		"answer": "datastore1"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "diskformat",
    		"text": "Enter disk format",
    		"accepted": ["thin", "thick"],
    		"answer": "thin"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_fqdn",
    		"text": "Enter fqdn or ip for your kubernetes cluster",
    		"answer": "xx.xx.xx.xx"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_port",
    		"text": "Enter port for your kubernetes cluster",
    		"answer": "443"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "auth_type",
    		"text": "What type of authentication ",
    		"accepted": ["basic", "certs"],
    		"answer": "basic"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "user",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user name: ",
    		"answer": "pks1.k8"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "password",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user password: ",
    		"answer": "admin"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "user",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user name: ",
    		"answer": "pks1.k8"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "password",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user password: ",
    		"answer": "admin"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "datastore",
    		"text": "Enter datastore name",
    		"answer": "datastore1"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "diskformat",
    		"text": "Enter disk format",
    		"accepted": ["thin", "thick"],
    		"answer": "thin"
    	}]
    }
