apiVersion: v1
kind: ConfigMap
metadata:
  name: apl-loc-deploy-delete
  namespace: applariat
data:
  apl-api: https://api.applariat.io/v1
  apl-api-key: a3a64cdfc9b214e019b25dd6699423aed01ac1db0ebc722a0502f705b01d41ba
  apl-cluster-mgr-tag: develop
  conf.json: |
      {
          "api-url": "https://api.applariat.io/v1",
          "propeller-ignore-ssl": "false",
          "rabbit-host": "amqp.applariat.io"
      }
  silent.json: |
    {
    	"questions": [{
            "section": "general",
            "title": "action",
            "text" : "Action",
            "accepted" : ["create", "import", "delete"],
            "answer": "delete"
        }, {
            "section": "general",
            "actions": ["delete"],
            "title": "loc_deploy_id",
            "text" : "Enter the loc_deploy_id you want to delete",
            "answer": "75c356ce-bbbf-46c8-8fe2-5a29b5e7eb75"
        }, {
            "section": "general",
            "actions": ["delete"],
            "title": "confirm_delete",
            "text" : "Are you sure you want to delete",
            "accepted" : ["yes", "no"],
            "answer" : "yes"
        } ]
    }
