apiVersion: batch/v1
kind: Job
metadata:
  name: apl-loc-deploy
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: apl-loc-deploy
        image: garreeoke/apl-loc-deploy
        env:
        - name: APL_API_KEY
          valueFrom:
            configMapKeyRef:
              name: pks
              key: apl-api-key
        - name: APL_API
          valueFrom:
            configMapKeyRef:
              name: pks
              key: apl-api
        volumeMounts:
          - name: silent-json
            mountPath: /apl-loc-deploy/interviews
      volumes:
        - name: silent-json
          configMap:
            name: pks
            items:
              - key: silent.json
                path: silent.json

      restartPolicy: Never
  backoffLimit: 4