apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permissive-binding
  namespace: applariat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubelet
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apl-loc-deploy-create
  namespace: default
data:
  apl-api: https://api.applariat.io/v1
  apl-api-key: a3a64cdfc9b214e019b25dd6699423aed01ac1db0ebc722a0502f705b01d41ba
  apl-cluster-mgr-tag: develop
  registry.json: |
      {
          "url": "harbor.mylab.com"
      }
  conf.json: |
      {
          "api-url": "https://api.applariat.io/v1",
          "propeller-ignore-ssl": "false",
          "rabbit-host": "amqp.applariat.io"
      }
  silent.json: |
    {
    	"questions": [{
    		"section": "general",
    		"title": "action",
    		"text": "Action",
    		"accepted": ["create", "import", "delete"],
    		"answer": "import"
    	}, {
    		"actions": ["create", "import"],
    		"section": "general",
    		"title": "loc_deploy_name",
    		"text": "Cluster name",
    		"answer": "pks_auto"
    	}, {
    		"actions": ["create", "import"],
    		"section": "general",
    		"title": "provider",
    		"text": "Cloud provider",
    		"accepted": ["aws", "azure", "gke", "metal", "vke", "vsphere"],
    		"answer": "vsphere"
    	}, {
            "section": "general",
            "actions": ["create", "import"],
            "title": "registry_url",
            "text" : "Enter registry url",
            "answer": "harbor.mylab.com/"
        }, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_fqdn",
    		"text": "Enter fqdn or ip for your kubernetes cluster",
    		"answer": "xx.xx.xx.xx"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "kube_port",
    		"text": "Enter port for your kubernetes cluster",
    		"answer": "443"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "auth_type",
    		"text": "What type of authentication ",
    		"accepted": ["basic", "certs"],
    		"answer": "basic"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "user",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user name: ",
    		"answer": "pks1.k8"
    	}, {
    		"actions": ["import"],
    		"section": "k8s",
    		"title": "password",
    		"type": "basic",
    		"text": "Enter kubernetes cluster user password: ",
    		"answer": "admin"
    	}, {
    		"actions": ["import"],
    		"section": "vsphere",
    		"title": "datastore",
    		"text": "Enter datastore name",
    		"answer": "datastoreComp"
    	}, {
            "actions": ["import"],
            "section": "vsphere",
            "title": "diskformat",
            "text": "Enter disk format",
            "accepted": ["thin", "zeroedthick", "eagerzeroedthick"],
            "answer": "thin"
        }]
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: apl-loc-deploy-create
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: apl-loc-deploy-create
        image: garreeoke/apl-loc-deploy
        imagePullPolicy: Always
        env:
        - name: APL_CONF
          valueFrom:
            configMapKeyRef:
              name: apl-loc-deploy-create
              key: conf.json
        - name: APL_API_KEY
          valueFrom:
            configMapKeyRef:
              name: apl-loc-deploy-create
              key: apl-api-key
        - name: APL_API
          valueFrom:
            configMapKeyRef:
              name: apl-loc-deploy-create
              key: apl-api
        - name: APL_LEAVE_JOB_POD
          value: "true"
        - name: PROPELLER_APL_BUILD_IMAGE_TAG
          value: develop
        - name: APL_BUILD_IMAGE_TAG
          value: develop
        - name: COMPONENT_BUILDER_APL_BUILD_IMAGE_TAG
          value: develop
        - name: APL_LAUNCHER
          value: k8s
        - name: NAMESPACE
          value: default
        - name: CLUSTER_MGR_APL_BUILD_IMAGE_TAG
          value: develop
        volumeMounts:
          - name: silent-json
            mountPath: /apl-loc-deploy/interviews
      volumes:
        - name: silent-json
          configMap:
            name: apl-loc-deploy-create
            items:
              - key: silent.json
                path: silent.json
      restartPolicy: Never
  backoffLimit: 4
---